# Generated by Django 4.1 on 2022-08-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(help_text='猫咪名称', max_length=64, verbose_name='猫咪名称')),
                ('birthday', models.DateField(help_text='出生日期', null=True, verbose_name='出生日期')),
                ('avatar', models.CharField(help_text='头像', max_length=255, null=True, verbose_name='头像')),
                ('gender', models.IntegerField(choices=[(0, '公'), (1, '母')], help_text='性别', verbose_name='性别')),
            ],
            options={
                'verbose_name': '猫咪信息',
                'verbose_name_plural': '猫咪信息',
                'db_table': 'cat',
            },
        ),
    ]
