# Generated by Django 4.1 on 2022-08-17 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('date', models.DateField(auto_now_add=True, help_text='记录体重时间', null=True, verbose_name='记录体重时间')),
                ('weight', models.IntegerField(help_text='体重', verbose_name='体重')),
                ('cat', models.ForeignKey(help_text='体重关联的猫咪', on_delete=django.db.models.deletion.DO_NOTHING, related_name='wg', to='system.cat', verbose_name='体重关联的猫咪')),
            ],
            options={
                'verbose_name': '猫咪体重',
                'verbose_name_plural': '猫咪体重',
                'db_table': 'weight',
            },
        ),
    ]
