# Generated by Django 4.1 on 2022-08-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_weight_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.FloatField(help_text='体重', verbose_name='体重'),
        ),
    ]
