# Generated by Django 4.1 on 2022-08-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_weight_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('priority', models.IntegerField(choices=[(0, '日常'), (1, '重要')], help_text='优先级', verbose_name='优先级')),
                ('title', models.TextField(help_text='标题', verbose_name='标题')),
                ('remark', models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('cat', models.ForeignKey(help_text='关联的猫咪', on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_wg', to='system.cat', verbose_name='关联的猫咪')),
            ],
            options={
                'verbose_name': '猫咪日常',
                'verbose_name_plural': '猫咪日常',
                'db_table': 'daily',
            },
        ),
    ]
