# Generated by Django 4.1 on 2022-08-20 07:38

import apps.system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileList',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('name', models.CharField(blank=True, help_text='名称', max_length=50, null=True, verbose_name='名称')),
                ('url', models.FileField(upload_to=apps.system.models.media_file_name)),
                ('md5sum', models.CharField(blank=True, help_text='文件md5', max_length=36, verbose_name='文件md5')),
            ],
            options={
                'verbose_name': '文件管理',
                'verbose_name_plural': '文件管理',
                'db_table': 'file_list.py',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['id'], 'verbose_name': '猫咪信息', 'verbose_name_plural': '猫咪信息'},
        ),
        migrations.AlterModelOptions(
            name='daily',
            options={'ordering': ['id'], 'verbose_name': '猫咪日常', 'verbose_name_plural': '猫咪日常'},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['date'], 'verbose_name': '猫咪体重', 'verbose_name_plural': '猫咪体重'},
        ),
    ]
