# Generated by Django 4.1 on 2022-08-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_filelist_alter_cat_options_alter_daily_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filelist',
            table='file_list',
        ),
    ]
