# Generated by Django 4.1 on 2022-08-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.CharField(help_text='头像', max_length=255, null=True, verbose_name='头像'),
        ),
    ]
